import type { ContractVersion, OrganizationalPolicy } from '../types/contract';
import { formatFriendlyDate, getDaysRemaining } from './deterministicDate';

export const LEGAL_DISCLAIMER_TEXT = `INFORMATION-MANAGEMENT TOOL NOTICE & DISCLAIMER
This document is generated by Contract Obligation and Renewal Assistant, an automated workflow and information-management utility. This tool provides operational data extraction, deterministic deadline calculations, and policy-rule comparison assistance. 
IT DOES NOT PROVIDE LEGAL ADVICE, LEGAL INTERPRETATIONS, OR FORMAL LEGAL COUNSEL. 
All extracted dates, obligations, and risk flags represent algorithmic extractions and must be reviewed, verified, and approved by qualified procurement and legal professionals prior to making commercial or legal commitments.`;

export function generateReviewedContractSummaryMarkdown(
  version: ContractVersion,
  policy?: OrganizationalPolicy
): string {
  const approvedObligations = (version?.obligations || []).filter((o) => o.status === 'APPROVED');
  const pendingObligations = (version?.obligations || []).filter((o) => o.status === 'PENDING');
  const staleObligations = (version?.obligations || []).filter((o) => o.status === 'STALE');
  
  const expiryVal = version?.dates?.expiryDate?.value || '';
  const isExpiryValid = Boolean(expiryVal && !expiryVal.includes('Unstated') && !expiryVal.includes('XXX'));
  const daysUntilExpiry = isExpiryValid ? getDaysRemaining(expiryVal) : null;
  const renewalDeadline = version?.renewal?.deterministicRenewalDeadline;
  const hasNoRenewal = 
    !version?.renewal ||
    version.renewal.type === 'NO_RENEWAL' ||
    !renewalDeadline ||
    renewalDeadline === 'N/A';
  const daysUntilRenewalNotice = hasNoRenewal || !renewalDeadline ? 0 : getDaysRemaining(renewalDeadline);

  let md = `# EXECUTIVE CONTRACT OBLIGATION & RENEWAL SUMMARY
**Document:** ${version?.fileName || 'Contract'} | **Version:** ${version?.versionLabel || 'v1.0'}  
**Generated Date:** ${new Date().toLocaleDateString()}  
**System Status:** Complete Audit Review

---

> ### ⚠️ ${LEGAL_DISCLAIMER_TEXT}

---

## 1. CONTRACT PARTIES & CORE PARAMETERS

| Parameter | Details | Status | Citation |
| :--- | :--- | :--- | :--- |
${(version?.parties || [])
  .map(
    (p) =>
      `| **${p.role}** | ${p.name} (${p.jurisdiction || 'N/A'}) | \`${p.status}\` | ${p.citation} |`
  )
  .join('\n')}
| **Effective Date** | ${formatFriendlyDate(version?.dates?.effectiveDate?.value || '')} | \`${version?.dates?.effectiveDate?.status || 'PENDING'}\` | ${version?.dates?.effectiveDate?.citation || 'N/A'} |
| **Initial Term** | ${version?.dates?.initialTerm?.value || 'Unstated'} | \`${version?.dates?.initialTerm?.status || 'PENDING'}\` | ${version?.dates?.initialTerm?.citation || 'N/A'} |
| **Contract Expiration** | ${isExpiryValid ? `${formatFriendlyDate(expiryVal)} (${daysUntilExpiry} days remaining)` : expiryVal || 'Unstated'} | \`${version?.dates?.expiryDate?.status || 'PENDING'}\` | ${version?.dates?.expiryDate?.citation || 'N/A'} |

---

## 2. DETERMINISTIC RENEWAL & TERMINATION TIMELINE

### Auto-Renewal Mechanism & Deadlines
- **Renewal Type:** ${hasNoRenewal ? 'No Auto-Renewal Provision (Fixed Term)' : version?.renewal?.type === 'AUTO_RENEWAL' ? 'Automatic Roll-over' : 'Fixed Term'} (${version?.renewal?.renewalPeriodText || 'Fixed Term'})
- **Required Notice Window:** ${(version?.renewal?.noticeWindowDays ?? 0) > 0 ? `${version.renewal.noticeWindowDays} calendar days advance written notice prior to term end` : 'N/A (Document contains no renewal clause)'}
- **Deterministic Non-Renewal Deadline:** **${hasNoRenewal || !renewalDeadline ? 'N/A — Not Mentioned in PDF' : formatFriendlyDate(renewalDeadline)}**
${hasNoRenewal || !renewalDeadline ? '- **Days Until Decision Cutoff:** N/A (Fixed term contract)' : `- **Days Until Decision Cutoff:** **${daysUntilRenewalNotice} calendar days remaining**`}
- **Calculation Formula:** \`${version?.renewal?.calculationFormula || 'N/A'}\`
- **Source Citation:** ${version?.renewal?.citation || 'N/A'}
- **Underlying Excerpt:** "${version?.renewal?.exactQuote || 'N/A'}"

### Deterministic Alert Trigger Schedule:
${version?.renewal?.reminders && version.renewal.reminders.length > 0
  ? version.renewal.reminders
      .map(
        (r) =>
          `- [ ] **${formatFriendlyDate(r.date)}** (T-${r.daysBefore} days): ${r.label} - *${r.triggerDescription}*`
      )
      .join('\n')
  : '- *No renewal alert triggers scheduled (Contract has no renewal clause and no renewal date mentioned in PDF).*'}

### Termination Framework
- **Termination for Convenience:** ${version?.termination?.hasConvenienceTermination ? 'Permitted (Customer unilateral)' : 'Not permitted'} (${version?.termination?.convenienceNoticeDays ?? 0} days advance notice required)
- **Termination for Cause:** ${version?.termination?.hasCauseTermination ? 'Permitted with' : 'No'} ${version?.termination?.causeCurePeriodDays ?? 0}-day written cure period
- **Notice Standard:** Permitted delivery via ${(version?.notice?.permittedMethods || []).join(', ')}. (Deemed received: ${version?.notice?.deemedReceivedDays ?? 0} business days)

---

## 3. VERIFIED OPERATIONAL OBLIGATIONS (${approvedObligations.length} Approved, ${staleObligations.length} Stale, ${pendingObligations.length} Pending)

### Approved Obligations
| Category | Obligation Title & Responsible Party | Target Date / Recurrence | Deterministic Reminders | Source Citation |
| :--- | :--- | :--- | :--- | :--- |
${approvedObligations
  .map(
    (o) =>
      `| \`${o.category}\` | **${o.title}**<br>*Party: ${o.responsibleParty}* | ${o.targetDate} (${o.recurrence}) | ${(o.reminders || []).length > 0 ? o.reminders[0].label : 'Ad-hoc'} | ${o.citation} |`
  )
  .join('\n')}

${
  staleObligations.length > 0
    ? `### ⚠️ Potentially Stale Items (Modified in new contract version - Re-verification required)
| Obligation | Reason Flagged Stale | Previous Value |
| :--- | :--- | :--- |
${staleObligations
  .map(
    (o) =>
      `| **${o.title}** | ${o.staleReason || 'Clause updated'} | ${o.previousVersionValue || 'N/A'} |`
  )
  .join('\n')}
`
    : ''
}

---

## 4. AMBIGUITIES, CLARIFICATION QUESTIONS & POLICY ALIGNMENT

${
  policy
    ? `### Organizational Policy Benchmark: ${policy.fileName}
${(policy.rules || [])
  .map(
    (r) =>
      `- **${r.ruleTitle}:** Standard is *${r.thresholdOrStandard}* (${r.citation})`
  )
  .join('\n')}
`
    : ''
}

### Identified Issues & Clarifications
${(version?.conflicts || [])
  .map(
    (c, i) => `#### ${i + 1}. [${c.severity}] ${c.title}
- **Type:** \`${c.conflictType}\` | **Review Status:** \`${c.status}\`
- **Description:** ${c.description}
- **Contract Source:** ${c.contractSectionA}
- **Quote:** "${c.quoteA}"
${c.policySection ? `- **Policy Conflict:** ${c.policySection} (Requirement: "${c.policyRequirement}")` : ''}
- **❓ AI Clarification Question:** *${c.clarificationQuestion}*
- **Operational Recommendation:** ${c.operationalRecommendation}
${c.userResolutionNote ? `- **User Resolution Note:** ${c.userResolutionNote}` : ''}
`
  )
  .join('\n')}

---

## 5. AUDIT TRAIL & USER CORRECTION LOG

| Timestamp | Item / Action | User / Engine | Notes |
| :--- | :--- | :--- | :--- |
${(version?.auditLog || [])
  .map(
    (a) =>
      `| ${new Date(a.timestamp).toLocaleString()} | \`${a.action}\` (${a.itemType}) | ${a.user} | ${a.notes || ''} |`
  )
  .join('\n')}

---
*Report generated securely by Contract Obligation and Renewal Assistant.*
`;

  return md;
}

export function downloadFile(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
